### ISSUE TITLE
Error in mutate_impl(.data, dots)

### ISSUE THREAD

**Issue by chamafelipe** [twang2218/pmap#2]
Hi twang2218, thanks for this great package. While trying to run your example, I'm getting the following error:

```
> eventlog <- eventdataR::sepsis %>%
   rename(
     timestamp = Complete_Timestamp,
     customer_id = Case_ID,
     event_name = Activity
   ) %>%
   select(timestamp, customer_id, event_name) %>%
   filter(!is.na(customer_id))
> p <- create_pmap(eventlog)
Error in mutate_impl(.data, dots) : 
  Column `type` must be length 15190 (the number of rows) or one, not 0

**Comment by twang2218** [comment]
Hi, @chamafelipe , thanks for your interest. The example on the `README.md` has been updated for the latest version `0.4.0`, which the `event_type` is not required any more for the `eventlog` data frame. However, it's still the case for the older version `0.3.2`, which is the current version on CRAN.

So, just add an extra column for `event_type` in the example if you are using `0.3.2` version:

```R
eventlog <- eventdataR::sepsis %>%
    rename(
        timestamp = Complete_Timestamp,
        customer_id = Case_ID,
        event_name = Activity
    ) %>%
    mutate(event_type = event_name) %>%
    select(timestamp, customer_id, event_name, event_type) %>%
    filter(!is.na(customer_id))

p <- create_pmap(eventlog)
render_pmap(p)
```

or, you can install the latest version from GitHub directly:

```$
devtools::install_github("twang2218/pmap")
```

then the example should work without any changes.

**Comment by chamafelipe** [comment]
Awesome, could get it to work.
Cheers!
